FROM mcr.microsoft.com/dotnet/sdk:10.0.100-alpine3.22 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "FileServer/FileServer.csproj" -o /app/publish -p:PublishTrimmed=true

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0.0-alpine3.22 AS app
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=""
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV FileServer_SettingsFilePath="/app/settings/appsettings.json"
ENTRYPOINT ["./FileServer"]
CMD []
