FROM mcr.microsoft.com/dotnet/sdk:10.0.100-alpine3.22 AS build
RUN apk add --no-cache clang cmake build-base zlib-dev openssl-dev openssl-libs-static
WORKDIR /src
COPY . .
RUN dotnet publish "FileServer/FileServer.csproj" -o /app/publish -p:FsPublishAot=true \
    -p:CppCompilerAndLinker=clang -p:StaticExecutable=true -p:StaticOpenSslLinking=true

FROM scratch AS app
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=""
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV FileServer_SettingsFilePath="/app/settings/appsettings.json"
ENTRYPOINT ["./FileServer"]
CMD []
