FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build
WORKDIR /repo
COPY . .
RUN dotnet publish src/FileServer -o /app/publish -p:PublishTrimmed=true

FROM mcr.microsoft.com/dotnet/runtime-deps:10.0-alpine AS app
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=""
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV FileServer_SettingsFilePath="/app/settings/appsettings.json"
ENTRYPOINT ["./FileServer"]
CMD []
